version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12 
    commands:
      - npm install

  build:
    commands:
      - export CLASSES_ADDRESS=https://classes.brekkedancecenter.com
      - npm run build
      - ./deploy/create-config-files.sh

artifacts:
  secondary-artifacts:
    buildResults:
      discard-paths: yes
      files:
        - "deploy/bdc-online.template.yml"
        - "bdc-online.*.config.json"
    siteFiles:
      base-directory: dist
      files:
        - "**/*"